import type { Category, Product, Review, FaqItem } from './types';

export const categories: Category[] = [
  {
    slug: 'gaming',
    name: 'مكاتب الألعاب',
    tagline: 'أداء لا يقهر',
    description: 'مكاتب مصممة لعشاق الألعاب بإضاءة RGB وأطراف مخصصة وحوامل شاشات مدمجة.',
    image: 'https://images.pexels.com/photos/30469973/pexels-photo-30469973.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'Gamepad2',
  },
  {
    slug: 'office',
    name: 'المكاتب الإدارية',
    tagline: 'أناقة تنفيذية',
    description: 'مكاتب إدارية فاخرة بخامات راقية تمنح مكتبك حضوراً تنفيذياً متميزاً.',
    image: 'https://images.pexels.com/photos/7658310/pexels-photo-7658310.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'Briefcase',
  },
  {
    slug: 'l-shaped',
    name: 'مكاتب L',
    tagline: 'مساحة أكبر',
    description: 'مكاتب بتصميم زاوية توفر مساحة عمل واسعة لمحبي الترتيب والإنتاجية.',
    image: 'https://images.pexels.com/photos/5001886/pexels-photo-5001886.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'CornerDownRight',
  },
  {
    slug: 'study',
    name: 'المكاتب الدراسية',
    tagline: 'تركيز وصفاء',
    description: 'مكاتب دراسية مريحة وبسيطة تناسب طلاب الجامعات والمدرسة.',
    image: 'https://images.pexels.com/photos/373904/pexels-photo-373904.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'GraduationCap',
  },
  {
    slug: 'accessories',
    name: 'الإكسسوارات',
    tagline: 'تفاصيل تصنع الفرق',
    description: 'حوامل شاشات، مصابيح مكتب، منظمات كابلات وكل ما يكمل مساحة عملك.',
    image: 'https://images.pexels.com/photos/30836164/pexels-photo-30836164.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'Lightbulb',
  },
  {
    slug: 'adjustable',
    name: 'المكاتب القابلة للتعديل',
    tagline: 'حركة مستمرة',
    description: 'مكاتب ذكية ترتفع وتنخفض لتناسب وضعية جلوسك أو وقوفك لراحة تدوم طويلاً.',
    image: 'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=900',
    icon: 'ArrowUpDown',
  },

];

const IMG = {
  gamingRGB: [
    'https://images.pexels.com/photos/30469973/pexels-photo-30469973.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/4317157/pexels-photo-4317157.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/13071304/pexels-photo-13071304.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  gamingWhite: [
    'https://images.pexels.com/photos/6489045/pexels-photo-6489045.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/28993064/pexels-photo-28993064.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/17789647/pexels-photo-17789647.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  gamingDark: [
    'https://images.pexels.com/photos/9794458/pexels-photo-9794458.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7199194/pexels-photo-7199194.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/33888373/pexels-photo-33888373.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  gamingNeon: [
    'https://images.pexels.com/photos/11633745/pexels-photo-11633745.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/17840843/pexels-photo-17840843.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/33050959/pexels-photo-33050959.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  officeWood: [
    'https://images.pexels.com/photos/7658310/pexels-photo-7658310.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/265101/pexels-photo-265101.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/1128207/pexels-photo-1128207.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  officeWhite: [
    'https://images.pexels.com/photos/1034650/pexels-photo-1034650.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/36123565/pexels-photo-36123565.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/346731/pexels-photo-346731.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  officeGlass: [
    'https://images.pexels.com/photos/13075330/pexels-photo-13075330.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/12913377/pexels-photo-12913377.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/265144/pexels-photo-265144.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  officeExecutive: [
    'https://images.pexels.com/photos/7071/space-desk-office-workspace.jpg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/6177596/pexels-photo-6177596.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/19089182/pexels-photo-19089182.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  studyWood: [
    'https://images.pexels.com/photos/373904/pexels-photo-373904.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8092421/pexels-photo-8092421.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/27524202/pexels-photo-27524202.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  studyMinimal: [
    'https://images.pexels.com/photos/12278554/pexels-photo-12278554.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8250975/pexels-photo-8250975.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/10567169/pexels-photo-10567169.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  studyCozy: [
    'https://images.pexels.com/photos/6934240/pexels-photo-6934240.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/13051218/pexels-photo-13051218.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/4231427/pexels-photo-4231427.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  lshapeCorner: [
    'https://images.pexels.com/photos/5001886/pexels-photo-5001886.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/38201401/pexels-photo-38201401.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/13806259/pexels-photo-13806259.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  lshapeWhite: [
    'https://images.pexels.com/photos/38525200/pexels-photo-38525200.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/3042508/pexels-photo-3042508.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8774461/pexels-photo-8774461.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  lshapeTech: [
    'https://images.pexels.com/photos/38201404/pexels-photo-38201404.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/15919233/pexels-photo-15919233.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7899236/pexels-photo-7899236.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  accessories: [
    'https://images.pexels.com/photos/30836164/pexels-photo-30836164.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/31198908/pexels-photo-31198908.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/27436633/pexels-photo-27436633.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  accessories2: [
    'https://images.pexels.com/photos/389819/pexels-photo-389819.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/10782398/pexels-photo-10782398.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/25450658/pexels-photo-25450658.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  chairBlack: [
    'https://images.pexels.com/photos/31726673/pexels-photo-31726673.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/30836165/pexels-photo-30836165.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/28461046/pexels-photo-28461046.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  chairOrange: [
    'https://images.pexels.com/photos/295480/pexels-photo-295480.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/18435547/pexels-photo-18435547.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/37550263/pexels-photo-37550263.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  chairDesigner: [
    'https://images.pexels.com/photos/7195522/pexels-photo-7195522.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/20648395/pexels-photo-20648395.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/31236092/pexels-photo-31236092.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  
  adjustableBlack: [
    'https://images.pexels.com/photos/5922213/pexels-photo-5922213.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7338604/pexels-photo-7338604.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7414922/pexels-photo-7414922.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  adjustableWhite: [
    'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/3183183/pexels-photo-3183183.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7338575/pexels-photo-7338575.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  adjustableWood: [
    'https://images.pexels.com/photos/5922180/pexels-photo-5922180.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/6634177/pexels-photo-6634177.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/4006126/pexels-photo-4006126.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  execLeather: [
    'https://images.pexels.com/photos/28993079/pexels-photo-28993079.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7658309/pexels-photo-7658309.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/20648405/pexels-photo-20648405.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  gamingPink: [
    'https://images.pexels.com/photos/7862660/pexels-photo-7862660.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7862670/pexels-photo-7862670.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7862663/pexels-photo-7862663.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  studyKids: [
    'https://images.pexels.com/photos/5063462/pexels-photo-5063462.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8111957/pexels-photo-8111957.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8111894/pexels-photo-8111894.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
hero: 'https://images.pexels.com/photos/30469973/pexels-photo-30469973.jpeg?auto=compress&cs=tinysrgb&w=1600',
};

const COLORS = {
  black: { name: 'أسود', hex: '#1A1A1A' },
  white: { name: 'أبيض', hex: '#F4F4F2' },
  walnut: { name: 'جوزي', hex: '#5B3A1F' },
  oak: { name: 'بلوطي', hex: '#C8A06A' },
  gray: { name: 'رمادي', hex: '#6B7280' },
  navy: { name: 'كحلي', hex: '#1E3A5F' },
  carbon: { name: 'كربون', hex: '#2B2B2B' },
  neon: { name: 'نيون', hex: '#00E5FF' },
};

export const products: Product[] = [

  {
    id: 'p21',
    slug: 'gaming-stealth-pro',
    name: 'مكتب الألعاب ستيلث برو',
    category: 'gaming',
    categoryName: 'مكاتب الألعاب',
    price: 9200,
    rating: 4.8,
    reviewCount: 175,
    inStock: true,
    stockCount: 8,
    shortSpecs: ['سطح كربوني 160 سم', 'إضاءة خلفية', 'حامل أكواب', 'شبكة كابلات'],
    materials: ['فولاذ مقاوم للصدأ', 'ألياف الكربون'],
    sizes: ['160 سم'],
    colors: [
      { ...COLORS.carbon, images: IMG.gamingDark },
      { ...COLORS.black, images: IMG.gamingRGB },
    ],
    description: 'مكتب الألعاب ستيلث بتصميمه المخفي الأنيق. يتميز بسطح مغطى بالكامل بألياف الكربون وإضاءة خلفية ناعمة تبرز جمالية غرفتك دون تشتيت انتباهك.',
    features: [
      'سطح مغطى بألياف الكربون بالكامل',
      'إضاءة خلفية مريحة للعين',
      'حامل أكواب وحامل سماعات',
      'شبكة كابلات سفلية مدمجة'
    ],
    dimensions: [
      { label: 'العرض', value: '160 سم' },
      { label: 'العمق', value: '75 سم' },
      { label: 'الارتفاع', value: '76 سم' },
      { label: 'الوزن', value: '34 كجم' },
    ],
    specs: [
      { label: 'الخامة الأساسية', value: 'فولاذ مقوى' },
      { label: 'تغطية السطح', value: 'ألياف الكربون' },
      { label: 'تحمل الوزن', value: '120 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'gaming-battlestation-x', 'gaming-pink-station'],
  },
  {
    id: 'p22',
    slug: 'executive-mahogany-desk',
    name: 'مكتب مهوجني الإداري',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 24500,
    oldPrice: 28000,
    rating: 5.0,
    reviewCount: 32,
    inStock: true,
    stockCount: 2,
    bestSeller: false,
    shortSpecs: ['خشب مهوجني صلب', 'تصميم عتيق', '5 أدراج', 'مساحة فائقة'],
    materials: ['خشب مهوجني', 'جلد طبيعي'],
    sizes: ['200 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.execLeather },
    ],
    description: 'الرمز المطلق للسلطة. مكتب مصنوع من خشب المهوجني الصلب بتصميم عتيق وخمسة أدراج توفر مساحة تخزين هائلة مع سطح مرصع بالجلد.',
    features: [
      'خشب مهوجني صلب معالج',
      '5 أدراج بأقفال نحاسية',
      'تصميم عتيق يعكس الرقي',
      'سطح كبير يمنح هيبة إدارية'
    ],
    dimensions: [
      { label: 'العرض', value: '200 سم' },
      { label: 'العمق', value: '95 سم' },
      { label: 'الارتفاع', value: '78 سم' },
      { label: 'الوزن', value: '85 كجم' },
    ],
    specs: [
      { label: 'الخامة الأساسية', value: 'خشب مهوجني صلب' },
      { label: 'الطلاء', value: 'يدوي عالي اللمعان' },
      { label: 'الأدراج', value: 'خشبية بالكامل' },
      { label: 'الضمان', value: '15 سنة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-leather-boss', 'executive-walnut-desk', 'office-glass-elegance'],
  },
  {
    id: 'p23',
    slug: 'lshape-glass-corner',
    name: 'الزاوية الزجاجية الحديثة',
    category: 'l-shaped',
    categoryName: 'مكاتب L',
    price: 13900,
    rating: 4.7,
    reviewCount: 94,
    inStock: true,
    stockCount: 6,
    shortSpecs: ['زجاج مقوى 10مم', 'هيكل ألمنيوم', 'تصميم L', 'مظهر عصري'],
    materials: ['زجاج مقوى', 'ألمنيوم'],
    sizes: ['160+120 سم'],
    colors: [
      { ...COLORS.black, images: IMG.officeGlass },
      { ...COLORS.white, images: IMG.lshapeWhite },
    ],
    description: 'يجمع هذا المكتب بين التصميم العملي لحرف L والمظهر العصري للزجاج الأسود والألمنيوم الفضي، ليخلق مساحة عمل ملهمة.',
    features: [
      'زجاج مقوى مقاوم للصدمات والخدوش',
      'هيكل ألمنيوم خفيف ومتين',
      'توزيع ذكي للمساحة',
      'أقدام قابلة للتعديل للحفاظ على الثبات'
    ],
    dimensions: [
      { label: 'السطح الرئيسي', value: '160 سم' },
      { label: 'السطح الجانبي', value: '120 سم' },
      { label: 'العمق', value: '65 سم' },
      { label: 'الوزن', value: '45 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'زجاج أسود 10مم' },
      { label: 'الهيكل', value: 'ألمنيوم مطلي' },
      { label: 'تحمل الوزن', value: '110 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['lshape-corner-pro', 'lshape-tech-station', 'office-glass-elegance'],
  },
  {
    id: 'p24',
    slug: 'study-minimalist-desk',
    name: 'مكتب المذاكرة المينيمال',
    category: 'study',
    categoryName: 'المكاتب الدراسية',
    price: 2890,
    oldPrice: 3500,
    rating: 4.5,
    reviewCount: 310,
    inStock: true,
    stockCount: 45,
    isNew: true,
    shortSpecs: ['تصميم صغير', 'درج واحد', 'سهل التجميع', 'سعر اقتصادي'],
    materials: ['خشب هندسي', 'معدن خفيف'],
    sizes: ['100 سم'],
    colors: [
      { ...COLORS.white, images: IMG.studyMinimal },
      { ...COLORS.oak, images: IMG.studyWood },
    ],
    description: 'الحل الأمثل للغرف الصغيرة وللطلاب الذين يحتاجون مساحة دراسة مركزة دون أي تشتيت. تصميم بسيط بدرج واحد.',
    features: [
      'تصميم مدمج يناسب أي غرفة',
      'درج عملي للقرطاسية',
      'سطح سهل التنظيف',
      'تجميع خلال 10 دقائق فقط'
    ],
    dimensions: [
      { label: 'العرض', value: '100 سم' },
      { label: 'العمق', value: '50 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '12 كجم' },
    ],
    specs: [
      { label: 'الخامة', value: 'MDF ملامين' },
      { label: 'الهيكل', value: 'أرجل معدنية رفيعة' },
      { label: 'تحمل الوزن', value: '40 كجم' },
      { label: 'الضمان', value: 'سنة واحدة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-scandi-oak', 'study-minimal-cozy', 'study-kids-grow'],
  },
  
  {
    id: 'p26',
    slug: 'accessory-foot-rest',
    name: 'مسند القدمين المريح',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 650,
    rating: 4.6,
    reviewCount: 420,
    inStock: true,
    stockCount: 60,
    shortSpecs: ['تصميم مريح', 'ارتفاع قابل للتعديل', 'سطح مانع للانزلاق', 'تخفيف الضغط'],
    materials: ['بلاستيك عالي الكثافة', 'معدن'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.accessories },
    ],
    description: 'يساعد مسند القدمين هذا على تحسين الدورة الدموية وتقليل الضغط على أسفل الظهر أثناء الجلوس لفترات طويلة بفضل تصميمه القابل للتعديل.',
    features: [
      'ثلاثة مستويات للارتفاع',
      'إمالة حرة تتكيف مع حركة القدم',
      'سطح مدلك للقدمين ومقاوم للانزلاق',
      'تصميم خفيف ومتين'
    ],
    dimensions: [
      { label: 'العرض', value: '45 سم' },
      { label: 'العمق', value: '35 سم' },
      { label: 'الارتفاع', value: '10 - 20 سم' },
      { label: 'الوزن', value: '1.5 كجم' },
    ],
    specs: [
      { label: 'الخامة', value: 'بلاستيك ABS' },
      { label: 'التعديل', value: '3 مستويات' },
      { label: 'الوظيفة', value: 'تحسين وضعية الجلوس' },
      { label: 'الضمان', value: 'سنة واحدة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['ergo-chair-pro', 'accessory-monitor-arm', 'adjustable-basic-stand'],
  },
  {
    id: 'p27',
    slug: 'accessory-headphone-stand',
    name: 'حامل سماعات RGB',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 890,
    rating: 4.8,
    reviewCount: 155,
    inStock: true,
    stockCount: 22,
    shortSpecs: ['إضاءة RGB', 'منافذ USB', 'قاعدة ثابتة', 'توافق شامل'],
    materials: ['ألمنيوم', 'أكريليك'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.accessories2 },
    ],
    description: 'حامل سماعات يضيف لمسة جمالية لمكتبك بفضل إضاءة RGB المتغيرة. يضم أيضاً منفذي USB إضافيين لتوصيل أجهزتك بكل سهولة.',
    features: [
      'إضاءة RGB بـ 9 تأثيرات مختلفة',
      '2 منفذ USB 2.0 لشحن أو نقل البيانات',
      'قاعدة بوزن إضافي لمنع الانقلاب',
      'حواف ناعمة لحماية وسادة السماعة'
    ],
    dimensions: [
      { label: 'الارتفاع', value: '28 سم' },
      { label: 'القاعدة', value: '12 × 12 سم' },
      { label: 'الوزن', value: '0.6 كجم' },
    ],
    specs: [
      { label: 'التوصيل', value: 'كابل USB مضفر' },
      { label: 'المنافذ', value: '2x USB 2.0' },
      { label: 'الإضاءة', value: 'RGB' },
      { label: 'الضمان', value: 'سنة واحدة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['gaming-stealth-pro', 'gaming-battlestation-x', 'gaming-pink-station'],
  },
  {
    id: 'p28',
    slug: 'gaming-ultra-wide',
    name: 'مكتب الألعاب العريض جداً',
    category: 'gaming',
    categoryName: 'مكاتب الألعاب',
    price: 11400,
    oldPrice: 13500,
    rating: 4.9,
    reviewCount: 201,
    inStock: true,
    stockCount: 7,
    shortSpecs: ['سطح 200 سم', 'يتحمل 4 شاشات', 'وسادة ماوس كاملة', 'تصميم وحشي'],
    materials: ['فولاذ صلب', 'MDF مقوى'],
    sizes: ['200 سم'],
    colors: [
      { ...COLORS.carbon, images: IMG.gamingDark },
      { ...COLORS.neon, images: IMG.gamingNeon },
    ],
    description: 'أضخم مكتب ألعاب في مجموعتنا! مصمم خصيصاً للمستخدمين الذين يحتاجون مساحة هائلة، يأتي مع وسادة ماوس تغطي السطح بالكامل.',
    features: [
      'وسادة ماوس مضادة للماء تغطي 100% من السطح',
      'مساحة تكفي لـ 3 أو 4 شاشات براحة تامة',
      'دعم إضافي في المنتصف لمنع التقوس',
      '4 منافذ لتنظيم الكابلات'
    ],
    dimensions: [
      { label: 'العرض', value: '200 سم' },
      { label: 'العمق', value: '80 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '45 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF مقسم لـ 3 أجزاء' },
      { label: 'الوسادة', value: 'قماش مايكرو فايبر' },
      { label: 'تحمل الوزن', value: '180 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'gaming-battlestation-x', 'accessory-monitor-arm'],
  },
  {
    id: 'p29',
    slug: 'office-conference-desk',
    name: 'مكتب الاجتماعات المصغر',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 15990,
    rating: 4.6,
    reviewCount: 42,
    inStock: true,
    stockCount: 4,
    shortSpecs: ['نصف دائري', 'يتسع لـ 4 أشخاص', 'منافذ طاقة بوب أب', 'خشب الجوز'],
    materials: ['خشب الجوز', 'فولاذ مجلفن'],
    sizes: ['180 سم', '220 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.officeWood },
      { ...COLORS.white, images: IMG.officeWhite },
    ],
    description: 'يجمع بين مكتب الإدارة وطاولة الاجتماعات. التصميم المنحني يسمح لك باستقبال حتى 4 أشخاص في مكتبك الخاص براحة واحترافية.',
    features: [
      'تصميم قوس مريح للاجتماعات الفردية',
      'وحدة طاقة بوب أب مدمجة في السطح (كهرباء + USB)',
      'سطح مقاوم للخدوش والسوائل',
      'حاجز سفلي يوفر الخصوصية'
    ],
    dimensions: [
      { label: 'العرض', value: '180 سم' },
      { label: 'العمق', value: '100 سم (الحد الأقصى)' },
      { label: 'الارتفاع', value: '76 سم' },
      { label: 'الوزن', value: '55 كجم' },
    ],
    specs: [
      { label: 'الخامة', value: 'خشب الجوز + HDF' },
      { label: 'وحدة الطاقة', value: '2 مقبس + 2 USB' },
      { label: 'السعة', value: '1 + 4 أشخاص' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'executive-leather-boss', 'ergo-chair-pro'],
  },
  {
    id: 'p30',
    slug: 'lshape-compact-student',
    name: 'المكتب الركني للطلاب',
    category: 'l-shaped',
    categoryName: 'مكاتب L',
    price: 7500,
    oldPrice: 8900,
    rating: 4.7,
    reviewCount: 215,
    inStock: true,
    stockCount: 18,
    bestSeller: true,
    shortSpecs: ['تصميم مدمج', 'مكتبة جانبية مدمجة', 'اللون الأبيض', 'عملي للغرف'],
    materials: ['خشب هندسي', 'MDF'],
    sizes: ['120+120 سم'],
    colors: [
      { ...COLORS.white, images: IMG.lshapeWhite },
      { ...COLORS.oak, images: IMG.studyWood },
    ],
    description: 'مكتب ركني صمم خصيصاً لغرف الشباب والطلاب. مساحة L مدمجة تأتي مع وحدة أرفف عمودية مدمجة للكتب والملفات.',
    features: [
      'يستغل الزوايا الميتة في الغرفة',
      'مكتبة مدمجة من 4 أرفف',
      'مثالي للاب توب والكتب معاً',
      'تصميم عصري بلون أبيض مشرق'
    ],
    dimensions: [
      { label: 'الجانبين', value: '120 × 120 سم' },
      { label: 'العمق', value: '50 سم' },
      { label: 'ارتفاع المكتب', value: '75 سم' },
      { label: 'ارتفاع المكتبة', value: '140 سم' },
    ],
    specs: [
      { label: 'الخامة', value: 'خشب MDF عالي الكثافة' },
      { label: 'الأرفف', value: '4 أرفف متينة' },
      { label: 'تحمل الوزن', value: '70 كجم' },
      { label: 'الضمان', value: '3 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-minimal-cozy', 'study-scandi-oak', 'accessory-desk-lamp'],
  },
   
  {
    id: 'p32',
    slug: 'accessory-mousepad-xl',
    name: 'وسادة ماوس الألعاب XL',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 450,
    oldPrice: 600,
    rating: 4.9,
    reviewCount: 530,
    inStock: true,
    stockCount: 120,
    bestSeller: true,
    shortSpecs: ['مقاس كبير 90×40', 'حواف مضيئة RGB', 'مضادة للماء', 'قاعدة مطاطية'],
    materials: ['قماش مايكرو فايبر', 'مطاط طبيعي'],
    sizes: ['90 × 40 سم'],
    colors: [
      { ...COLORS.black, images: IMG.accessories },
    ],
    description: 'وسادة ماوس كبيرة جداً تغطي مساحة الكيبورد والماوس معاً. توفر سطحاً فائق النعومة لحركة الماوس وتتميز بإضاءة RGB محيطية بـ 14 وضعاً.',
    features: [
      'إضاءة RGB تتصل بـ USB مع 14 تأثير مختلف',
      'سطح قماشي دقيق مقاوم لانسكاب السوائل',
      'قاعدة من المطاط الطبيعي تمنع الانزلاق تماماً',
      'حواف مخيطة لمتانة تدوم سنوات'
    ],
    dimensions: [
      { label: 'العرض', value: '90 سم' },
      { label: 'العمق', value: '40 سم' },
      { label: 'السماكة', value: '4 مم' },
      { label: 'الوزن', value: '0.8 كجم' },
    ],
    specs: [
      { label: 'الخامة', value: 'مطاط + قماش' },
      { label: 'التوصيل', value: 'كابل Micro USB' },
      { label: 'مقاومة الماء', value: 'نعم' },
      { label: 'الضمان', value: 'سنة واحدة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['gaming-neon-arena', 'gaming-stealth-pro', 'pro-gamer-rgb'],
  },
  {
    id: 'p33',
    slug: 'office-folding-desk',
    name: 'المكتب القابل للطي',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 3200,
    rating: 4.5,
    reviewCount: 164,
    inStock: true,
    stockCount: 30,
    shortSpecs: ['يطوى في ثوانٍ', 'لا يحتاج لتجميع', 'سهل التخزين', 'هيكل متين'],
    materials: ['خشب هندسي', 'فولاذ'],
    sizes: ['100 سم'],
    colors: [
      { ...COLORS.oak, images: IMG.studyWood },
      { ...COLORS.black, images: IMG.officeGlass },
    ],
    description: 'المكتب المثالي للمساحات المؤقتة والعمل من المنزل. يصلك مجمعاً بالكامل ويطوى في ثوانٍ لسهولة التخزين تحت السرير أو خلف الباب.',
    features: [
      'لا يحتاج إلى أي تركيب أو مسامير',
      'مفصلات فولاذية قوية لسهولة الطي والفرد',
      'يشغل مساحة 5 سم فقط عند طيه',
      'خفيف الوزن وسهل النقل'
    ],
    dimensions: [
      { label: 'العرض', value: '100 سم' },
      { label: 'العمق', value: '50 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'سمك الطي', value: '5 سم' },
    ],
    specs: [
      { label: 'الخامة', value: 'MDF ملامين' },
      { label: 'الهيكل', value: 'معدن مطلي' },
      { label: 'تحمل الوزن', value: '50 كجم' },
      { label: 'الضمان', value: 'سنة واحدة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-minimalist-desk', 'study-minimal-cozy', 'accessory-desk-lamp'],
  },
  {
    id: 'p34',
    slug: 'executive-credenza',
    name: 'وحدة التخزين الإدارية (كردنزا)',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 11500,
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    stockCount: 8,
    shortSpecs: ['الرفيق للمكاتب', 'مساحة تخزين ضخمة', 'أبواب منزلقة', 'خشب جوزي'],
    materials: ['خشب جوزي', 'MDF'],
    sizes: ['160 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.execLeather },
      { ...COLORS.oak, images: IMG.studyWood },
    ],
    description: 'القطعة المكملة للمكتب التنفيذي. توفر مساحة تخزين أنيقة خلف المكتب لحفظ الملفات والطابعة وأدوات الضيافة، بنفس خامات مكتبك الجوزي الفاخر.',
    features: [
      'أبواب منزلقة لسهولة الفتح في المساحات الضيقة',
      'أرفف داخلية قابلة لتعديل الارتفاع',
      'سطح يتحمل وضع الطابعات وآلات القهوة',
      'أقفال أمان للحفاظ على سرية المستندات'
    ],
    dimensions: [
      { label: 'العرض', value: '160 سم' },
      { label: 'العمق', value: '45 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '48 كجم' },
    ],
    specs: [
      { label: 'الخامة', value: 'قشرة جوز طبيعي' },
      { label: 'الأبواب', value: 'منزلقة (جرار)' },
      { label: 'الأقفال', value: 'قفل أسطواني مركزي' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'executive-leather-boss', 'executive-mahogany-desk'],
  },


  
  {
    id: 'p16',
    slug: 'executive-leather-boss',
    name: 'مكتب الإدارة الكلاسيكي',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 18990,
    oldPrice: 22000,
    rating: 5.0,
    reviewCount: 45,
    inStock: true,
    stockCount: 3,
    shortSpecs: ['سطح جلد طبيعي', 'خشب صلب', 'تصميم كلاسيكي', '3 أدراج'],
    materials: ['خشب بلوط صلب', 'جلد طبيعي'],
    sizes: ['180 سم', '200 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.execLeather },
    ],
    description: 'تحفة فنية كلاسيكية لغرف الإدارة التنفيذية. سطح مطعم بالجلد الطبيعي الفاخر وهيكل من الخشب الصلب المحفور يدوياً.',
    features: [
      'سطح مبطن بالجلد الطبيعي المعالج',
      'ثلاثة أدراج واسعة بنظام أمان',
      'تفاصيل كلاسيكية محفورة يدوياً',
      'عمر افتراضي طويل جداً'
    ],
    dimensions: [
      { label: 'العرض', value: '180 سم' },
      { label: 'العمق', value: '85 سم' },
      { label: 'الارتفاع', value: '76 سم' },
      { label: 'الوزن', value: '65 كجم' },
    ],
    specs: [
      { label: 'الخامة الأساسية', value: 'خشب بلوط صلب' },
      { label: 'تطعيم السطح', value: 'جلد بقري طبيعي' },
      { label: 'الأدراج', value: 'مجاري هيدروليك' },
      { label: 'الضمان', value: '10 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'office-glass-elegance', 'accessory-desk-lamp'],
  },
 
   
  {
    id: 'p19',
    slug: 'lshape-executive-corner',
    name: 'مكتب الزاوية التنفيذي',
    category: 'l-shaped',
    categoryName: 'مكاتب L',
    price: 16500,
    rating: 4.9,
    reviewCount: 78,
    inStock: true,
    stockCount: 4,
    shortSpecs: ['خشب زان', 'أدراج مدمجة', 'مساحة هائلة', 'تصميم مودرن'],
    materials: ['خشب زان صلب', 'زجاج مقوى', 'فولاذ'],
    sizes: ['200+160 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.lshapeCorner },
      { ...COLORS.black, images: IMG.lshapeTech },
    ],
    description: 'للمديرين الباحثين عن الفخامة والمساحة. مكتب زاوية من خشب الزان بتطعيمات زجاجية ووحدة أدراج متحركة مدمجة.',
    features: [
      'مساحة عمل مزدوجة تكفي لاجتماعات مصغرة',
      'وحدة مكونة من 3 أدراج بقفل مركزي',
      'خشب زان معالج ضد الخدش والرطوبة',
      'ممر مخفي للكابلات على طول المكتبين'
    ],
    dimensions: [
      { label: 'الجناح الرئيسي', value: '200 سم' },
      { label: 'الجناح الفرعي', value: '160 سم' },
      { label: 'العمق', value: '80/60 سم' },
      { label: 'الارتفاع', value: '76 سم' },
    ],
    specs: [
      { label: 'الخامة', value: 'خشب زان + زجاج 10مم' },
      { label: 'الهيكل', value: 'دواعم فولاذية' },
      { label: 'الوحدة المرفقة', value: 'أدراج بعجل' },
      { label: 'الضمان', value: '10 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'lshape-corner-pro', 'executive-leather-boss'],
  },
  

  {
    id: 'p1',
    slug: 'pro-gamer-rgb',
    name: 'مكتب الألعاب برو RGB',
    category: 'gaming',
    categoryName: 'مكاتب الألعاب',
    price: 8990,
    oldPrice: 11490,
    rating: 4.9,
    reviewCount: 218,
    inStock: true,
    stockCount: 12,
    bestSeller: true,
    shortSpecs: ['سطح 140×70 سم', 'إضاءة RGB قابلة للبرمجة', 'حامل شاشة مدمج', 'ومرر كابلات'],
    materials: ['فولاذ مطلي', 'خشب MDF', 'زجاج مقوى'],
    sizes: ['140 سم', '160 سم'],
    colors: [
      { ...COLORS.black, images: IMG.gamingRGB },
      { ...COLORS.white, images: IMG.gamingWhite },
      { ...COLORS.neon, images: IMG.gamingNeon },
      { ...COLORS.carbon, images: IMG.gamingDark },
    ],
    description: 'مكتب الألعاب برو RGB يجمع بين المتانة والجمال في تصميم واحد. سطح كبير مقاوم للخدش مع شريط إضاءة RGB قابل للبرمجة عبر تطبيق الهاتف، وحامل شاشة مزدوج مدمج، ونظام إدارة كابلات مخفي يمنح مكتبك مظهراً نظيفاً واحترافياً.',
    features: [
      'إضاءة RGB بـ 16 مليون لون قابلة للتحكم عبر التطبيق',
      'سطح مقاوم للخدش والحرارة حتى 180°م',
      'حامل شاشة مزدوج قابل للتعديل في الارتفاع',
      'منظم كابلات مخفي مع 4 منافذ',
      'أرجل فولاذية قابلة للضبط لضمان الاستواء التام',
      'حافة مريحة للمعصم بدعم اليد الطويلة',
    ],
    dimensions: [
      { label: 'العرض', value: '140 سم' },
      { label: 'العمق', value: '70 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '32 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'خشب MDF مقاوم للخدش' },
      { label: 'الهيكل', value: 'فولاذ مطلي بطلاء إلكتروستاتيكي' },
      { label: 'تحمل الوزن', value: '120 كجم' },
      { label: 'الإضاءة', value: 'RGB مع تحكم بلوتوث' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['gaming-neon-arena', 'gaming-battlestation-x', 'accessory-monitor-arm'],
  },
  {
    id: 'p2',
    slug: 'gaming-neon-arena',
    name: 'مكتب نيون أرينا',
    category: 'gaming',
    categoryName: 'مكاتب الألعاب',
    price: 7650,
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    stockCount: 8,
    shortSpecs: ['سطح 160 سم', 'إضاءة محيطية', 'مجسم هوائي', 'مجلد سماعات'],
    materials: ['فولاذ', 'خشب MDF'],
    sizes: ['160 سم'],
    colors: [
      { ...COLORS.black, images: IMG.gamingNeon },
      { ...COLORS.carbon, images: IMG.gamingRGB },
      { ...COLORS.white, images: IMG.gamingWhite },
    ],
    description: 'تصميم رياضي عدائي مع إضاءة محيطية متدرجة وحامل سماعات مدمج. مثالي لجلسات الألعاب الطويلة بفضل السطح الواسع والدعم المريح للذراعين.',
    features: [
      'إضاءة محيطية متدرجة الألوان',
      'حامل سماعات قابل للفك والتركيب',
      'سطح مضاد للانعكاسات للتركيز على الشاشة',
      'أرجل متعددة المستويات لثبات استثنائي',
    ],
    dimensions: [
      { label: 'العرض', value: '160 سم' },
      { label: 'العمق', value: '65 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '28 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'خشب MDF مضاد للانعكاس' },
      { label: 'الهيكل', value: 'فولاذ مقاوم للصدأ' },
      { label: 'تحمل الوزن', value: '100 كجم' },
      { label: 'الإضاءة', value: 'إضاءة محيطية ثابتة' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'gaming-battlestation-x', 'accessory-cable-tray'],
  },
  {
    id: 'p3',
    slug: 'gaming-battlestation-x',
    name: 'محطة القتال X',
    category: 'gaming',
    categoryName: 'مكاتب الألعاب',
    price: 10290,
    oldPrice: 12990,
    rating: 4.9,
    reviewCount: 94,
    inStock: true,
    stockCount: 5,
    bestSeller: true,
    shortSpecs: ['سطح 180 سم', 'حامل 3 شاشات', 'إضاءة RGB', 'شاحن USB مدمج'],
    materials: ['فولاذ مطلي', 'خشب MDF فاخر'],
    sizes: ['180 سم'],
    colors: [
      { ...COLORS.black, images: IMG.gamingDark },
      { ...COLORS.white, images: IMG.gamingWhite },
      { ...COLORS.neon, images: IMG.gamingNeon },
    ],
    description: 'محطة قتال متكاملة بثلاث شاشات وشاحن USB مدمج. للأساطير الذين يديرون عدة شاشات في وقت واحد دون أي تنازل عن الجمال.',
    features: [
      'حامل ثلاثي للشاشات قابل للإمالة والدوران',
      'مخرجان USB للشحن السريع',
      'سطح فاخر بطلاء ناعم الملمس',
      'قاعدة خلفية لإخفاء الكابلات بالكامل',
    ],
    dimensions: [
      { label: 'العرض', value: '180 سم' },
      { label: 'العمق', value: '70 سم' },
      { label: 'الارتفاع', value: '78 سم' },
      { label: 'الوزن', value: '38 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF بطبقة ناعمة' },
      { label: 'الهيكل', value: 'فولاذ مزدوج' },
      { label: 'تحمل الوزن', value: '140 كجم' },
      { label: 'الإضاءة', value: 'RGB + USB شحن' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'gaming-neon-arena', 'accessory-monitor-arm'],
  },
  {
    id: 'p4',
    slug: 'executive-walnut-desk',
    name: 'المكتب التنفيذي الجوزي',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 13450,
    oldPrice: 15900,
    rating: 4.9,
    reviewCount: 73,
    inStock: true,
    stockCount: 6,
    bestSeller: true,
    shortSpecs: ['سطح 160×80 سم', 'خشب جوزي صلب', 'درج أمان', 'ممر كابلات'],
    materials: ['خشب الجوز الصلب', 'فولاذ'],
    sizes: ['160 سم', '180 سم'],
    colors: [
      { ...COLORS.walnut, images: IMG.officeWood },
      { ...COLORS.oak, images: IMG.officeExecutive },
      { ...COLORS.black, images: IMG.officeGlass },
    ],
    description: 'مكتب تنفيذي يفرض حضوره. خشب جوزي صلب بسطح واسع ودرج أمان بمزلاج، يمنح قائد العمل لمسة من الفخامة والثبات.',
    features: [
      'خشب جوزي طبيعي بطلاء يدوي',
      'درج أمان بمزلاج ومفاتيح',
      'ممر كابلات مخفي بسدادة معدنية',
      'قاعدة فولاذية لثبات مطلق',
    ],
    dimensions: [
      { label: 'العرض', value: '160 سم' },
      { label: 'العمق', value: '80 سم' },
      { label: 'الارتفاع', value: '76 سم' },
      { label: 'الوزن', value: '45 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'خشب جوزي صلب' },
      { label: 'الهيكل', value: 'فولاذ مطوي' },
      { label: 'تحمل الوزن', value: '150 كجم' },
      { label: 'الدرج', value: 'درج أمان بمزلاج' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['office-glass-elegance', 'office-minimal-white', 'accessory-desk-lamp'],
  },
  {
    id: 'p5',
    slug: 'office-glass-elegance',
    name: 'مكتب الزجاج أناقة',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 9890,
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    stockCount: 9,
    shortSpecs: ['سطح زجاجي مقوى', 'قاعدة فولاذية', 'درج مخفي', 'تصميم عائم'],
    materials: ['زجاج مقوى', 'فولاذ'],
    sizes: ['150 سم'],
    colors: [
      { ...COLORS.black, images: IMG.officeGlass },
      { ...COLORS.white, images: IMG.officeWhite },
      { ...COLORS.gray, images: IMG.officeWood },
    ],
    description: 'مكتب زجاجي عائم يبث أناقة معاصرة في أي مكتب. زجاج مقوّى بسماكة 12 ملم وقاعدة فولاذية أنيقة.',
    features: [
      'زجاج مقوّى 12 ملم مضاد للكسر',
      'قاعدة فولاذية بتصميم عائم',
      'درج جانبي مخفي',
      'سهل التنظيف ومقاوم للبقع',
    ],
    dimensions: [
      { label: 'العرض', value: '150 سم' },
      { label: 'العمق', value: '70 سم' },
      { label: 'الارتفاع', value: '75 سم' },
      { label: 'الوزن', value: '36 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'زجاج مقوّى 12 مم' },
      { label: 'الهيكل', value: 'فولاذ مطلي' },
      { label: 'تحمل الوزن', value: '90 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'office-minimal-white', 'accessory-monitor-arm'],
  },
  {
    id: 'p6',
    slug: 'office-minimal-white',
    name: 'المكتب الأبيض البسيط',
    category: 'office',
    categoryName: 'المكاتب الإدارية',
    price: 6450,
    oldPrice: 7990,
    rating: 4.6,
    reviewCount: 187,
    inStock: true,
    stockCount: 14,
    shortSpecs: ['سطح 140 سم', 'تصميم بسيط', 'أرجل بيضاء', 'خفيف الوزن'],
    materials: ['خشب MDF', 'ألمنيوم'],
    sizes: ['140 سم', '160 سم'],
    colors: [
      { ...COLORS.white, images: IMG.officeWhite },
      { ...COLORS.oak, images: IMG.studyWood },
      { ...COLORS.gray, images: IMG.officeGlass },
    ],
    description: 'مكتب أبيض بسيط يناسب المساحات العصرية. تصميم خفيف وأنيق يمنح المكتب إحساساً بالاتساع والنقاء.',
    features: [
      'سطح أبيض لامع مقاوم للخدش',
      'أرجل ألمنيوم قابلة للضبط',
      'تركيب سهل خلال 20 دقيقة',
      'مناسب للمساحات الصغيرة',
    ],
    dimensions: [
      { label: 'العرض', value: '140 سم' },
      { label: 'العمق', value: '65 سم' },
      { label: 'الارتفاع', value: '74 سم' },
      { label: 'الوزن', value: '21 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF أبيض لامع' },
      { label: 'الهيكل', value: 'ألمنيوم خفيف' },
      { label: 'تحمل الوزن', value: '80 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['executive-walnut-desk', 'study-scandi-oak', 'accessory-desk-lamp'],
  },
  {
    id: 'p7',
    slug: 'lshape-corner-pro',
    name: 'مكتب الزاوية برو',
    category: 'l-shaped',
    categoryName: 'مكاتب L',
    price: 11200,
    oldPrice: 13900,
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
    stockCount: 7,
    bestSeller: true,
    shortSpecs: ['تصميم زاوية L', 'سطحان 160+120', 'حامل شاشة', 'إدارة كابلات'],
    materials: ['خشب MDF', 'فولاذ'],
    sizes: ['160+120 سم', '180+140 سم'],
    colors: [
      { ...COLORS.black, images: IMG.lshapeCorner },
      { ...COLORS.white, images: IMG.lshapeWhite },
      { ...COLORS.carbon, images: IMG.lshapeTech },
    ],
    description: 'مكتب زاوية بتصميم L يمنحك مساحتين منفصلتين للعمل والشاشات. مثالي للمبرمجين والمصممين والمحترفين الذين يحتاجون مساحة أكبر.',
    features: [
      'سطحان منفصلان بزوايا مدروسة',
      'حامل شاشة قابل للتركيب في أي طرف',
      'أرجل فولاذية متصلة لثبات كامل',
      'منظم كابلات في كلا السطحين',
    ],
    dimensions: [
      { label: 'السطح الرئيسي', value: '160 سم' },
      { label: 'السطح الجانبي', value: '120 سم' },
      { label: 'العمق', value: '65 سم' },
      { label: 'الوزن', value: '42 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF مقاوم للخدش' },
      { label: 'الهيكل', value: 'فولاذ مزدوج' },
      { label: 'تحمل الوزن', value: '130 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['lshape-tech-station', 'pro-gamer-rgb', 'accessory-monitor-arm'],
  },
  {
    id: 'p8',
    slug: 'lshape-tech-station',
    name: 'محطة L التقنية',
    category: 'l-shaped',
    categoryName: 'مكاتب L',
    price: 12990,
    rating: 4.7,
    reviewCount: 68,
    inStock: true,
    stockCount: 4,
    shortSpecs: ['تصميم L', 'إضاءة RGB', 'شاحن USB', 'ممر كابلات ذكي'],
    materials: ['خشب MDF', 'فولاذ', 'زجاج'],
    sizes: ['180+140 سم'],
    colors: [
      { ...COLORS.carbon, images: IMG.lshapeTech },
      { ...COLORS.black, images: IMG.lshapeCorner },
      { ...COLORS.white, images: IMG.lshapeWhite },
    ],
    description: 'محطة L متكاملة بإضاءة RGB وشاحن USB مدمج. للباحثين عن مكتب يجمع بين مساحة العمل الكبيرة والقدرات التقنية.',
    features: [
      'إضاءة RGB متصلة بالتطبيق',
      'شاحن USB-C سريع 65 واط',
      'حامل شاشة قابل للتعديل',
      'قاعدة قابلة للتمديد حسب الحاجة',
    ],
    dimensions: [
      { label: 'السطح الرئيسي', value: '180 سم' },
      { label: 'السطح الجانبي', value: '140 سم' },
      { label: 'العمق', value: '70 سم' },
      { label: 'الوزن', value: '48 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF + زجاج مقوى' },
      { label: 'الهيكل', value: 'فولاذ مزدوج' },
      { label: 'تحمل الوزن', value: '140 كجم' },
      { label: 'الإضاءة', value: 'RGB + USB-C' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['lshape-corner-pro', 'gaming-battlestation-x', 'accessory-cable-tray'],
  },
  {
    id: 'p9',
    slug: 'study-scandi-oak',
    name: 'مكتب دراسي بلوطي إسكندنافي',
    category: 'study',
    categoryName: 'المكاتب الدراسية',
    price: 4290,
    oldPrice: 5490,
    rating: 4.8,
    reviewCount: 264,
    inStock: true,
    stockCount: 22,
    bestSeller: true,
    shortSpecs: ['سطح 120 سم', 'خشب بلوطي', 'درج جانبي', 'تصميم بسيط'],
    materials: ['خشب البلوط', 'خشب MDF'],
    sizes: ['120 سم', '140 سم'],
    colors: [
      { ...COLORS.oak, images: IMG.studyWood },
      { ...COLORS.white, images: IMG.studyMinimal },
      { ...COLORS.walnut, images: IMG.studyCozy },
    ],
    description: 'مكتب دراسي بتصميم إسكندنافي دافئ. خشب بلوطي طبيعي بدرج جانبي عملي، مثالي لغرف الطلاب وأماكن المذاكرة.',
    features: [
      'خشب بلوطي طبيعي بحبيبات واضحة',
      'درج جانبي بسلاسة انزلاق',
      'حافة مستديرة لراحة المعصم',
      'وزن خفيف وسهل النقل',
    ],
    dimensions: [
      { label: 'العرض', value: '120 سم' },
      { label: 'العمق', value: '60 سم' },
      { label: 'الارتفاع', value: '74 سم' },
      { label: 'الوزن', value: '16 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'خشب بلوطي طبيعي' },
      { label: 'الهيكل', value: 'MDF مدهون' },
      { label: 'تحمل الوزن', value: '60 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-minimal-cozy', 'office-minimal-white', 'accessory-desk-lamp'],
  },
  {
    id: 'p10',
    slug: 'study-minimal-cozy',
    name: 'المكتب الدراسي الدافئ',
    category: 'study',
    categoryName: 'المكاتب الدراسية',
    price: 3490,
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    stockCount: 18,
    shortSpecs: ['سطح 110 سم', 'تصميم دافئ', 'رف سفلي', 'خفيف الوزن'],
    materials: ['خشب MDF', 'خشب البلوط'],
    sizes: ['110 سم', '130 سم'],
    colors: [
      { ...COLORS.white, images: IMG.studyMinimal },
      { ...COLORS.oak, images: IMG.studyWood },
      { ...COLORS.walnut, images: IMG.studyCozy },
    ],
    description: 'مكتب دراسي دافئ بتصميم بسيط ورف سفلي للكتب. يناسب الطلاب الباحثين عن مساحة مذاكرة مريحة وأنيقة.',
    features: [
      'رف سفلي للكتب والقرطاسية',
      'سطح بأطراف مستديرة آمنة',
      'سهل التجميع خلال 15 دقيقة',
      'ألوان دافئة تبعث على الهدوء',
    ],
    dimensions: [
      { label: 'العرض', value: '110 سم' },
      { label: 'العمق', value: '55 سم' },
      { label: 'الارتفاع', value: '74 سم' },
      { label: 'الوزن', value: '13 كجم' },
    ],
    specs: [
      { label: 'نوع السطح', value: 'MDF بطبقة بلوط' },
      { label: 'الهيكل', value: 'MDF متين' },
      { label: 'تحمل الوزن', value: '50 كجم' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-scandi-oak', 'office-minimal-white', 'accessory-desk-lamp'],
  },
  {
    id: 'p11',
    slug: 'ergo-chair-pro',
    name: 'كرسي المكتب المريح برو',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 8790,
    oldPrice: 10990,
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 10,
    bestSeller: true,
    shortSpecs: ['دعم قطني متحرك', 'مسند رأس قابل للتعديل', 'ذراعان 4D', 'شبكة تنفس'],
    materials: ['شبكة تنفس', 'ألمنيوم', 'فولاذ'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.chairBlack },
      { ...COLORS.walnut, images: IMG.chairOrange },
      { ...COLORS.gray, images: IMG.chairDesigner },
    ],
    description: 'كرسي مكتب مريح بتصميم إرغونومي متقدم. دعم قطني متحرك يتكيف مع انحناء ظهرك، ومسند رأس قابل للتعديل، وذراعان رباعي الأبعاد.',
    features: [
      'دعم قطني متحرك بثلاث زوايا',
      'مسند رأس قابل للارتفاع والإمالة',
      'ذراعان 4D قابلان للضبط بكل الاتجاهات',
      'شبكة تنفس عالية الجودة',
      'عجلات سيليكون لا تترك أثراً',
    ],
    dimensions: [
      { label: 'العرض', value: '68 سم' },
      { label: 'العمق', value: '70 سم' },
      { label: 'الارتفاع', value: '120-130 سم' },
      { label: 'تحمل الوزن', value: '150 كجم' },
    ],
    specs: [
      { label: 'المقعد', value: 'شبكة تنفس ألمانية' },
      { label: 'الهيكل', value: 'ألمنيوم مقوّى' },
      { label: 'الذراعان', value: '4D قابل للضبط' },
      { label: 'الآلية', value: 'إمالة متزامنة' },
      { label: 'الضمان', value: '5 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'executive-walnut-desk', 'accessory-monitor-arm'],
  },
  {
    id: 'p12',
    slug: 'accessory-monitor-arm',
    name: 'حامل شاشة قابل للتعديل',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 1290,
    oldPrice: 1790,
    rating: 4.7,
    reviewCount: 421,
    inStock: true,
    stockCount: 35,
    shortSpecs: ['لشاشة واحدة', 'حتى 32 بوصة', 'تعديل كامل', 'تركيب بدون ثقب'],
    materials: ['ألمنيوم', 'فولاذ'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.accessories },
      { ...COLORS.white, images: IMG.accessories2 },
    ],
    description: 'حامل شاشة من الألمنيوم يوفر تعديلاً كاملاً في الارتفاع والإمالة والدوران. يدعم الشاشات حتى 32 بوصة مع تركيب بدون ثقب المكتب.',
    features: [
      'يدعم شاشات 17 إلى 32 بوصة',
      'تعديل الارتفاع بنظام زنبركي',
      'إمالة ±90° ودوران 360°',
      'مشبك بدون ثقب يحمي سطح المكتب',
      'ممر كابلات مدمج',
    ],
    dimensions: [
      { label: 'ارتفاع التمدد', value: '52 سم' },
      { label: 'الذراع', value: '38 سم' },
      { label: 'تحمل الوزن', value: '9 كجم' },
      { label: 'حجم الشاشة', value: '17-32 بوصة' },
    ],
    specs: [
      { label: 'الخامة', value: 'ألمنيوم متين' },
      { label: 'التركيب', value: 'مشبك بدون ثقب' },
      { label: 'التوافق', value: 'VESA 75/100' },
      { label: 'الضمان', value: '3 سنوات' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['pro-gamer-rgb', 'lshape-corner-pro', 'ergo-chair-pro'],
  },
  {
    id: 'p13',
    slug: 'accessory-desk-lamp',
    name: 'مصباح المكتب الذكي',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 890,
    rating: 4.8,
    reviewCount: 287,
    inStock: true,
    stockCount: 40,
    isNew: true,
    shortSpecs: ['إضاءة LED', 'تعديل الحرارة', 'منفذ شحن', 'تحكم باللمس'],
    materials: ['ألمنيوم', 'بلاستيك ABS'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.accessories2 },
      { ...COLORS.white, images: IMG.accessories },
    ],
    description: 'مصباح مكتب ذكي بإضاءة LED قابلة للتعديل في درجة الحرارة والشدة. مزود بمنفذ شحن USB ومنطقة شحن لاسلكي للهاتف.',
    features: [
      '5 درجات حرارة لون من 2700K إلى 6500K',
      'شدة إضاءة من 5% إلى 100%',
      'منطقة شحن لاسلكي 10W',
      'منفذ USB للشحن السريع',
      'مؤقت إطفاء تلقائي',
    ],
    dimensions: [
      { label: 'الارتفاع', value: '45 سم' },
      { label: 'القاعدة', value: '18 سم' },
      { label: 'الذراع', value: '40 سم' },
      { label: 'القدرة', value: '10W + USB' },
    ],
    specs: [
      { label: 'الإضاءة', value: 'LED قابل للتعديل' },
      { label: 'الحرارة', value: '2700K - 6500K' },
      { label: 'الشحن', value: 'لاسلكي 10W + USB' },
      { label: 'التحكم', value: 'لمسي' },
      { label: 'الضمان', value: '2 سنة' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['study-scandi-oak', 'executive-walnut-desk', 'accessory-monitor-arm'],
  },
  {
    id: 'p14',
    slug: 'accessory-cable-tray',
    name: 'منظم الكابلات المخفي',
    category: 'accessories',
    categoryName: 'الإكسسوارات',
    price: 390,
    oldPrice: 590,
    rating: 4.6,
    reviewCount: 178,
    inStock: false,
    stockCount: 0,
    shortSpecs: ['تركيب تحت المكتب', 'سعة كبيرة', 'شبك معدني', 'سهل التركيب'],
    materials: ['فولاذ مطلي'],
    sizes: ['مقاس موحد'],
    colors: [
      { ...COLORS.black, images: IMG.accessories },
    ],
    description: 'منظم كابلات معدني يركب تحت سطح المكتب ليخفي كل الفوضى. سعة كبيرة تستوعب أجهزة الشحن وموزعات الكهرباء.',
    features: [
      'تركيب بمسامير أو شريط لاصق قوي',
      'شبك معدني يسمح بتهوية الأجهزة',
      'سعة 8 لتر تستوعب لوحة كهرباء',
      'متوافق مع كل مكاتبنا',
    ],
    dimensions: [
      { label: 'العرض', value: '40 سم' },
      { label: 'العمق', value: '15 سم' },
      { label: 'الارتفاع', value: '12 سم' },
      { label: 'السعة', value: '8 لتر' },
    ],
    specs: [
      { label: 'الخامة', value: 'فولاذ مطلي' },
      { label: 'التركيب', value: 'مسامير أو لاصق' },
      { label: 'السعة', value: '8 لتر' },
      { label: 'الضمان', value: 'سنتان' },
      { label: 'بلد الصنع', value: 'مصر' },
    ],
    relatedSlugs: ['lshape-tech-station', 'gaming-battlestation-x', 'accessory-monitor-arm'],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    name: 'أحمد الشناوي',
    city: 'القاهرة',
    rating: 5,
    date: 'يوليو 2025',
    title: 'تجربة فاخرة بكل المقاييس',
    body: 'اشتريت مكتب الألعاب برو RGB ومنذ اليوم الأول شعرت بالفرق. الإضاءة رائعة والسطح متين جداً، والتركيب كان سهلاً بفضل الكتيب الواضح. يستحق كل جنيه.',
    productSlug: 'pro-gamer-rgb',
    avatarColor: '#F59E0B',
  },
  {
    id: 'r2',
    name: 'منى عبد الرحمن',
    city: 'الجيزة',
    rating: 5,
    date: 'يونيو 2025',
    title: 'أناقة تنفيذية حقيقية',
    body: 'المكتب التنفيذي الجوزي أضاف لمسة فخامة لمكتبي. الخامة ممتازة والدرج بأمان يعمل بسلاسة. خدمة العملاء ساعدتني في اختيار المقاس المناسب لمساحتي.',
    productSlug: 'executive-walnut-desk',
    avatarColor: '#1E293B',
  },
  {
    id: 'r3',
    name: 'كريم فؤاد',
    city: 'الإسكندرية',
    rating: 5,
    date: 'أغسطس 2025',
    title: 'أفضل مكتب زاوية جربته',
    body: 'مكتب الزاوية برو غيّر طريقة عملي تماماً. أصبح لدي مساحة للشاشات ومساحة للكتابة في نفس الوقت. متانة الهيكل فاقت توقعاتي.',
    productSlug: 'lshape-corner-pro',
    avatarColor: '#0F172A',
  },
  {
    id: 'r4',
    name: 'سارة مصطفى',
    city: 'القاهرة',
    rating: 4,
    date: 'مايو 2025',
    title: 'مكتب دراسي مثالي لابني',
    body: 'اشتريت المكتب الدراسي البلوتي لابني والنتيجة رائعة. التصميم بسيط وعملي والدرج جانبي مفيد جداً. التوصيل كان سريعاً والحزم وصلت سليمة.',
    productSlug: 'study-scandi-oak',
    avatarColor: '#F59E0B',
  },
  {
    id: 'r5',
    name: 'يوسف حسن',
    city: 'طنطا',
    rating: 5,
    date: 'يوليو 2025',
    title: 'كرسي مريح يستحق الثمن',
    body: 'كرسي المكتب المريح برو أنقذ ظهري بعد ساعات العمل الطويلة. الدعم القطني يتكيف مع ظهري بشكل مذهل والذراعان قابلان للضبط بكل سهولة.',
    productSlug: 'ergo-chair-pro',
    avatarColor: '#1E293B',
  },
  {
    id: 'r6',
    name: 'نورا إبراهيم',
    city: 'المنصورة',
    rating: 5,
    date: 'أغسطس 2025',
    title: 'إكسسوارات تكمّل المكتب',
    body: 'حامل الشاشة والمصباح الذكي أكملا مكتبي بشكل مثالي. التركيب سهل والجودة عالية. أصبح مكتب يبدو وكأنه مصمم احترافياً.',
    productSlug: 'accessory-monitor-arm',
    avatarColor: '#0F172A',
  },
];

export const faqs: FaqItem[] = [
  {
    q: 'هل يشمل الضمان جميع المنتجات؟',
    a: 'نعم، جميع مكاتبنا تأتي بضمان 5 سنوات يشمل الهيكل والسطح وآليات الأدراج. الإكسسوارات تأتي بضمان من سنتين إلى 3 سنوات حسب المنتج.',
  },
  {
    q: 'كم تستغرق مدة التوصيل داخل مصر؟',
    a: 'التوصيل داخل القاهرة الكبرى يستغرق من 2 إلى 4 أيام عمل، أما المحافظات فمن 3 إلى 6 أيام عمل. التركيب متاح في القاهرة والجيزة والإسكندرية مقابل رسوم رمزية.',
  },
  {
    q: 'هل يمكنني طلب مقاسات مخصصة؟',
    a: 'بالتأكيد. نوفر خدمة التصنيع حسب الطلب لمكاتب الإدارية والمكاتب L. تواصل معنا عبر واتساب مع المقاسات المطلوبة وسيرد عليك فريق التصميم خلال 24 ساعة.',
  },
  {
    q: 'هل التركيب متاح أم أقوم به بنفسي؟',
    a: 'كلاهما متاح. جميع مكاتبنا تأتي بكتيب تركيب واضح وأدوات أساسية لمن يفضل التركيب الذاتي. كما نوفر خدمة تركيب احترافية في القاهرة والجيزة والإسكندرية.',
  },
  {
    q: 'ما طرق الدفع المتاحة؟',
    a: 'نوفر الدفع عند الاستلام في جميع المحافظات، بالإضافة إلى الدفع الإلكتروني عبر بطاقات Visa و Mastercard والتحويل البنكي للطلبات الكبيرة.',
  },
  {
    q: 'هل يمكنني إرجاع المنتج إن لم يعجبني؟',
    a: 'نعم، لديك 14 يوماً من تاريخ الاستلام لإرجاع المنتج بحالته الأصلية مع التغليف. يستثنى من ذلك المنتجات المصنعة حسب الطلب.',
  },
];
